filetype off                              " required

call plug#begin('~/.vim/plugged')

Plug 'tomtom/tcomment_vim'                " Commenting grids
Plug 'airblade/vim-gitgutter'
Plug 'dense-analysis/ale'
Plug 'majutsushi/tagbar'
Plug 'ervandew/supertab'
Plug 'bling/vim-airline'                  " Status bar
Plug 'maralla/completor.vim'
Plug 'flazz/vim-colorschemes'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdtree'

call plug#end()
filetype plugin indent on                 " required

colorscheme night                         " also have used: night, molokai, afterglow, peaksea
syntax enable                             " enable syntax processing-

set nocompatible                          " vundle requires vim not to be compatible with vi
let g:completor_auto_trigger = 0
" inoremap <expr> <S-Tab> pumvisible() ? "<C-N>" : "<C-R>=completor#do('complete')<CR>"
